development:
  adapter: postgresql
  encoding: unicode
  database: angipl_development
  host: localhost
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: angipl_test
  host: localhost
  pool: 5
